
name: CI

on: pull_request

jobs:

  test:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:

      matrix:

        toolchain:
          - ubuntu-latest-clang
          - ubuntu-latest-gcc

        include:
          - toolchain: ubuntu-latest-clang
            os: ubuntu-latest
            c_compiler: clang
            cxx_compiler: clang++

          - toolchain: ubuntu-latest-gcc
            os: ubuntu-latest
            c_compiler: cc
            cxx_compiler: g++

    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure
      working-directory: test
      run: cmake -S . -B build ${{ matrix.cmake_opts }}
      env:
        CC: ${{ matrix.c_compiler }}
        CXX: ${{ matrix.cxx_compiler }}

    - name: Build for ${{ matrix.os }} with ${{ matrix.compiler }}
      working-directory: test
      run: cmake --build build

    - name: Test
      working-directory: test/build
      run: ./tests
