
name: Static Analysis

on: pull_request

jobs:

  static_analysis:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:

      matrix:

        toolchain:
          - ubuntu-latest

        include:
          - toolchain: ubuntu-latest
            os: ubuntu-latest
            compiler: clang

    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Analyze
      uses: JacobDomagala/StaticAnalysis@master
      with:
        clang_tidy_args: --extra-arg=-Iinclude --extra-arg=-std=c++17
        cppcheck_args: --verbose --enable=all --inline-suppr --inconclusive --suppress=missingInclude --suppress='*:argparse/test/d*.hpp'
        init_script: tools/static_analysis_setup.sh
        verbose: true
