
name: Static Analysis

on: pull_request

jobs:

  static_analysis:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:

      matrix:

        toolchain:
          - ubuntu-latest

        include:
          - toolchain: ubuntu-latest
            os: ubuntu-latest
            compiler: clang

    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Analyze
      uses: JacobDomagala/StaticAnalysis@master
      with:
        clang_tidy_args: >-
          --config-file=$GITHUB_WORKSPACE/.clang-tidy
          --extra-arg=-I$GITHUB_WORKSPACE/include --extra-arg=-std=c++17
        cppcheck_args: >-
          --enable=all --inconclusive --inline-suppr
          -i$GITHUB_WORKSPACE/test/main.cpp
          -i$GITHUB_WORKSPACE/test/test_*.cpp
          --suppress=missingInclude
          --suppress='*:$GITHUB_WORKSPACE/test/doctest.hpp'
        init_script: tools/static_analysis_setup.sh
